name: Slack PR Notifier

on:
  pull_request:
    types: [opened]

jobs:
  slackNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "*📣 New Pull Request Created!*",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*\n*Author:* ${{ github.event.pull_request.user.login }}"
                }
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
